### ISSUE TITLE
[APP] Swipe left for menu / go back

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#63]
enable swipe interactions

**Comment by pellarboss** [comment]
swipe left on main pages = show menu
swipe left on sub pages = go back to main page

**Comment by DefiHunter** [comment]
@madtocc  The swipe back does not work when you viewing a specific NFT , Please investigate

**Comment by DefiHunter** [comment]
Same goes for when you click on "XCUR" or "USDXC" in the wallet. If you find anymore as well lmk @madtocc

**Comment by madtocc** [comment]
@DefiHunter it is fixed on the new build. It is not yet available for iOS 😅

https://user-images.githubusercontent.com/12486417/125847138-280f127e-1c93-4a78-93b0-bc373d963ee0.mov

**Comment by DefiHunter** [comment]
Strange, I'm testing on a samsung galaxy s10 plus

**Comment by madtocc** [comment]
🤔 on Android it should not have a problem. swipe gesture = back button... just tried here and it works... can you try on latest build I have sent on slack a few min ago?

**Comment by madtocc** [comment]
https://user-images.githubusercontent.com/12486417/125850775-4bc185dd-b821-4f25-84e7-60dd9aa7d4df.mp4

**Comment by DefiHunter** [comment]
Strange , i just did that and tested and I'm still having the same issue.

**Comment by madtocc** [comment]
the issue was related to the iOS. It didn't have swipe interaction when we pull some information when the back button is pressed and this was fixed.
I tried in 3 different Android phones and I'm not able to reproduce it. 
iOS was tested in simulator and on physical device and it works fine as well.
