### ISSUE TITLE
Desktop - Areas not working correctly

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#690]
**Describe the bug**
Please see below the areas that are not showing correctly for the desktop marketplace: 

**Screenshots**

1.  Collections that have nothing in them are still showing. As discussed with Marco a few weeks back, if the collection doesn't have any NFTs, don't show on the collection tab. 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/88379508/179440829-ae9685ac-e517-4b9f-8d59-1f21e014c9ec.png">

2. Some collections don't seem to have any data, yet they have several sales. 

i.e. Dracattus Graph
<img width="607" alt="image" src="https://user-images.githubusercontent.com/88379508/179441254-7369d89f-2ab6-4f67-926e-209415ef07ad.png">

3. On some desktops, it appears that the arrow graphic for the banners is being cut. It works for mine but Steve reported the issue. 

https://user-images.githubusercontent.com/88379508/179442234-b5f7d32c-ec8d-4d05-9e2d-dc6828792ebc.MOV

**Comment by Catherineanne91** [comment]
![green candle](https://user-images.githubusercontent.com/93180831/179445205-2dacafbe-e508-4fb1-bd1f-eb57c18c3795.jpg)

**Comment by Catherineanne91** [comment]
Features/Functionalities currently in the app that we can add in the desktop app:

Update Collection - Tool to help users transfer an NFT to another collection

Edit Attributes - Add or edit attributes for NFT

View Offers

View Stats

![green candle](https://user-images.githubusercontent.com/93180831/179445507-5f8adbb1-0a46-4a21-b780-c6256aa62dc1.jpg)

**Comment by Catherineanne91** [comment]
Improvement we can apply both in the mobile and desktop app:

Allow users to change their Percent Royalty IF NFT has not been sold yet through: "EDIT" button (same button they use when they edit the price

**Comment by TheMad-J-Hatter** [comment]
Newly minted NFT via desktop doesn't show in mobile app: 

The user minted a new video format NFT via the desktop app, but when trying to view this same NFT on the mobile app, it does not show anything but a blank screen. Please fix this issue so video NFT can be seen on both platforms. 

![Screenshot_20220718-094900_CURATE](https://user-images.githubusercontent.com/88379508/179551562-4c53b4cd-cd26-4757-a86c-b1eea8c1cec1.jpg)

<img width="994" alt="image" src="https://user-images.githubusercontent.com/88379508/179551918-1a885d9c-f163-4c9a-a902-4414ddf97c0a.png">

**Comment by TheMad-J-Hatter** [comment]
**Desktop - NFT video is cut short when being viewed on desktop.**

The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting. 

User Key: f129010ae8ce30b8bdff63a68040bdb169d5
Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)

https://user-images.githubusercontent.com/88379508/180027070-367c0c6d-5aa4-43a4-a8cb-d1b1e873e818.mov


https://user-images.githubusercontent.com/88379508/180027087-98e4e289-c64c-4d5f-9d69-0add83410479.mov

**Comment by TheMad-J-Hatter** [comment]
**Add filter on collection page**
1. There is no filter for collections. This can be useful if you want to filter all 'Gold' Stake boosting NFTs as well as sort by 'For Sale Only' 

**Option A and then B**
2. An sort by Option A and then Option B i.e. Sort By 'Price - Low to High' and then by 'For Sale Only'. Please allow this feature. 

**Sort By not working correctly**
3. 'For Sale Only' sort by not working correctly. 

Process: 

a. Select Sort By - For Sale Only
b. Increase number of NFTs showing per page to 50
c. For Sale Only is still active BUT the NFTs showing are not for sale.  

<img width="988" alt="image" src="https://user-images.githubusercontent.com/88379508/180040835-33acde00-fb09-40ac-b660-a9cb3b92b900.png">

**Comment by Pellar-Spike** [comment]
> **Add filter on collection page**
> 
> 1. There is no filter for collections. This can be useful if you want to filter all 'Gold' Stake boosting NFTs as well as sort by 'For Sale Only'
> 
> **Option A and then B** 2. An sort by Option A and then Option B i.e. Sort By 'Price - Low to High' and then by 'For Sale Only'. Please allow this feature.
> 
> **Sort By not working correctly** 3. 'For Sale Only' sort by not working correctly.
> 
> Process:
> 
> a. Select Sort By - For Sale Only b. Increase number of NFTs showing per page to 50 c. For Sale Only is still active BUT the NFTs showing are not for sale.
> 
> <img alt="image" width="988" src="https://user-images.githubusercontent.com/88379508/180040835-33acde00-fb09-40ac-b660-a9cb3b92b900.png">

@TheMad-J-Hatter  I fixed it

**Comment by TheMad-J-Hatter** [comment]
*Add 'Collection' option on selection bar**

<img width="902" alt="image" src="https://user-images.githubusercontent.com/88379508/180238701-251072dd-cf06-4823-ac5b-7efea5f6f5ee.png">

**Comment by TheMad-J-Hatter** [comment]
**404 Error when selecting 'Profile' as guest user**

When a guest user clicks on 'Profile, My Collections, Mint or Saved' buttons on the selection bar, please can they be reverted to a page that says, Login or Register please. 

![image](https://user-images.githubusercontent.com/88379508/180278591-30631650-2789-401d-a85b-70b039840b0c.png)

**Comment by TheMad-J-Hatter** [comment]
**Ability to update collection when not logged in or it being the owner of the collection**

I just noticed the little 'edit' pencil at the side and noticed that I was not logged in or the fact I wasn't the owner of the collection. This is on the 'develop' marketplace (see URL in image) but thought it was strange. 

Please advise?

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/88379508/180798767-ff5603d0-a4f4-4f47-af26-ddb6169df19a.png">

<img width="982" alt="image" src="https://user-images.githubusercontent.com/88379508/180799440-8f20a57b-26a2-4e51-be61-2298dccd5663.png">

**Comment by TheMad-J-Hatter** [comment]
Hi @pellarboss, hope all is well? 

Would you mind if we started fixing some of these bugs please? 

Thanks

**Comment by Pellar-Spike** [comment]
> _Add 'Collection' option on selection bar_*
> 
> <img alt="image" width="902" src="https://user-images.githubusercontent.com/88379508/180238701-251072dd-cf06-4823-ac5b-7efea5f6f5ee.png">

Added

**Comment by Pellar-LocNgo** [comment]
> 

1. fixed

**Comment by Pellar-Spike** [comment]
> **404 Error when selecting 'Profile' as guest user**
> 
> When a guest user clicks on 'Profile, My Collections, Mint or Saved' buttons on the selection bar, please can they be reverted to a page that says, Login or Register please.
> 
> ![image](https://user-images.githubusercontent.com/88379508/180278591-30631650-2789-401d-a85b-70b039840b0c.png)

Fixed

**Comment by Pellar-Spike** [comment]
> **Ability to update collection when not logged in or it being the owner of the collection**
> 
> I just noticed the little 'edit' pencil at the side and noticed that I was not logged in or the fact I wasn't the owner of the collection. This is on the 'develop' marketplace (see URL in image) but thought it was strange.
> 
> Please advise?
> 
> <img alt="image" width="1014" src="https://user-images.githubusercontent.com/88379508/180798767-ff5603d0-a4f4-4f47-af26-ddb6169df19a.png">
> 
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/88379508/180799440-8f20a57b-26a2-4e51-be61-2298dccd5663.png">

Fixed

**Comment by TheMad-J-Hatter** [comment]
> **Add filter on collection page**
> 
> 1. There is no filter for collections. This can be useful if you want to filter all 'Gold' Stake boosting NFTs as well as sort by 'For Sale Only'
> 
> **Option A and then B** 2. An sort by Option A and then Option B i.e. Sort By 'Price - Low to High' and then by 'For Sale Only'. Please allow this feature.
> 
> **Sort By not working correctly** 3. 'For Sale Only' sort by not working correctly.
> 
> Process:
> 
> a. Select Sort By - For Sale Only b. Increase number of NFTs showing per page to 50 c. For Sale Only is still active BUT the NFTs showing are not for sale.
> 
> <img alt="image" width="988" src="https://user-images.githubusercontent.com/88379508/180040835-33acde00-fb09-40ac-b660-a9cb3b92b900.png">

@Pellar-LocNgo, thanks for fixing but there was another enhancement in this comment. Please see Option A and then B comment.

**Comment by TheMad-J-Hatter** [comment]
> **Desktop - NFT video is cut short when being viewed on desktop.**
> 
> The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.
> 
> User Key: f129010ae8ce30b8bdff63a68040bdb169d5 Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)
> 
>  Video_1.mov 
>  Video.mov

@Pellar-LocNgo, this is yet to be fixed. The video still seems to be only showing part of the video NFT before resetting which is not how the artist envisaged it to be displayed. A second issue is when enlarging the video, it does not come up full screen. Kindly, please fix.

**Comment by TheMad-J-Hatter** [comment]
> Newly minted NFT via desktop doesn't show in mobile app:
> 
> The user minted a new video format NFT via the desktop app, but when trying to view this same NFT on the mobile app, it does not show anything but a blank screen. Please fix this issue so video NFT can be seen on both platforms.
> 
> ![Screenshot_20220718-094900_CURATE](https://user-images.githubusercontent.com/88379508/179551562-4c53b4cd-cd26-4757-a86c-b1eea8c1cec1.jpg)
> 
> <img alt="image" width="994" src="https://user-images.githubusercontent.com/88379508/179551918-1a885d9c-f163-4c9a-a902-4414ddf97c0a.png">

@Pellar-LocNgo this issue still requires fixing please; the mobile app does not show the video NFT.

**Comment by TheMad-J-Hatter** [comment]
Hi @pellarboss, we still have a few remaining issues here. 

If you'd like me to split them up, I will. Please advise.

**Comment by Pellar-Spike** [comment]
> > **Desktop - NFT video is cut short when being viewed on desktop.**
> > The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.
> > User Key: f129010ae8ce30b8bdff63a68040bdb169d5 Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)
> > Video_1.mov
> > Video.mov
> 
> @Pellar-LocNgo, this is yet to be fixed. The video still seems to be only showing part of the video NFT before resetting which is not how the artist envisaged it to be displayed. A second issue is when enlarging the video, it does not come up full screen. Kindly, please fix.

@TheMad-J-Hatter  HTML 5 currently does not support some formats with .mov videos, so for .mov videos we will use images to display (in your example we are using gif images)
Please use a different format video for NFT

**Comment by Pellar-Spike** [comment]
I can't reproduce the bug, can you give me the info device, size screen, ... ?
![Screenshot from 2022-08-04 15-13-33](https://user-images.githubusercontent.com/93480407/182798829-d2014288-4e04-4ce3-9b5b-e229e64a89a0.png)

**Comment by TheMad-J-Hatter** [comment]
> I can't reproduce the bug, can you give me the info device, size screen, ... ? ![Screenshot from 2022-08-04 15-13-33](https://user-images.githubusercontent.com/93480407/182798829-d2014288-4e04-4ce3-9b5b-e229e64a89a0.png)

I have asked Steve who originally saw this and he has confirmed, this visual issue no longer exists.

**Comment by TheMad-J-Hatter** [comment]
> 

@Pellar-LocNgo . Ok, this is an issue as the artist would have to burn these NFTs and upload the entire batch again using a different format. 

He has over 100 NFTs and doing this manually would take ages. Please advise?

**Comment by TheMad-J-Hatter** [comment]
> > > **Desktop - NFT video is cut short when being viewed on desktop.**
> > > The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.
> > > User Key: f129010ae8ce30b8bdff63a68040bdb169d5 Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)
> > > Video_1.mov
> > > Video.mov
> > 
> > 
> > @Pellar-LocNgo, this is yet to be fixed. The video still seems to be only showing part of the video NFT before resetting which is not how the artist envisaged it to be displayed. A second issue is when enlarging the video, it does not come up full screen. Kindly, please fix.
> 
> @TheMad-J-Hatter HTML 5 currently does not support some formats with .mov videos, so for .mov videos, we will use images to display (in your example we are using gif images) Please use a different format video for NFT

@Pellar-LocNgo . Ok, this is an issue as the artist would have to burn these NFTs and upload the entire batch again using a different format.

He has over 100 NFTs and doing this manually would take ages. Please advise.

**Comment by TheMad-J-Hatter** [comment]
> > **Add filter on collection page**
> > 
> > 1. There is no filter for collections. This can be useful if you want to filter all 'Gold' Stake boosting NFTs as well as sort by 'For Sale Only'
> > 
> > **Option A and then B** 2. An sort by Option A and then Option B i.e. Sort By 'Price - Low to High' and then by 'For Sale Only'. Please allow this feature.
> > **Sort By not working correctly** 3. 'For Sale Only' sort by not working correctly.
> > Process:
> > a. Select Sort By - For Sale Only b. Increase number of NFTs showing per page to 50 c. For Sale Only is still active BUT the NFTs showing are not for sale.
> > <img alt="image" width="988" src="https://user-images.githubusercontent.com/88379508/180040835-33acde00-fb09-40ac-b660-a9cb3b92b900.png">
> 
> @Pellar-LocNgo, thanks for fixing but there was another enhancement in this comment. Please see Option A and then B comment.

This issue/enhancement is now fixed.

**Comment by TheMad-J-Hatter** [comment]
> ![green candle](https://user-images.githubusercontent.com/93180831/179445205-2dacafbe-e508-4fb1-bd1f-eb57c18c3795.jpg)

@Pellar-LocNgo please add when possible.

**Comment by TheMad-J-Hatter** [comment]
> Features/Functionalities currently in the app that we can add in the desktop app:
> 
> Update Collection - Tool to help users transfer an NFT to another collection
> 
> Edit Attributes - Add or edit attributes for NFT
> 
> View Offers
> 
> View Stats
> 
> ![green candle](https://user-images.githubusercontent.com/93180831/179445507-5f8adbb1-0a46-4a21-b780-c6256aa62dc1.jpg)

@Pellar-LocNgo. Please add when possible, thanks.

**Comment by TheMad-J-Hatter** [comment]
> > > > **Desktop - NFT video is cut short when being viewed on desktop.**
> > > > The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.
> > > > User Key: f129010ae8ce30b8bdff63a68040bdb169d5 Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)
> > > > Video_1.mov
> > > > Video.mov
> > > 
> > > 
> > > @Pellar-LocNgo, this is yet to be fixed. The video still seems to be only showing part of the video NFT before resetting which is not how the artist envisaged it to be displayed. A second issue is when enlarging the video, it does not come up full screen. Kindly, please fix.
> > 
> > @TheMad-J-Hatter HTML 5 currently does not support some formats with .mov videos, so for .mov videos, we will use images to display (in your example we are using gif images) Please use a different format video for NFT
> 
> @Pellar-LocNgo . Ok, this is an issue as the artist would have to burn these NFTs and upload the entire batch again using a different format.
> 
> He has over 100 NFTs and doing this manually would take ages. Please advise.


Hi @Pellar-LocNgo,  any update on how we can solve this issue. How can the artists correct this issue, can they burn their NFTs from the platform and re-mint in a different format?

**Comment by TheMad-J-Hatter** [comment]
> > > > > **Desktop - NFT video is cut short when being viewed on desktop.**
> > > > > The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.
> > > > > User Key: f129010ae8ce30b8bdff63a68040bdb169d5 Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)
> > > > > Video_1.mov
> > > > > Video.mov
> > > > 
> > > > 
> > > > @Pellar-LocNgo, this is yet to be fixed. The video still seems to be only showing part of the video NFT before resetting which is not how the artist envisaged it to be displayed. A second issue is when enlarging the video, it does not come up full screen. Kindly, please fix.
> > > 
> > > 
> > > @TheMad-J-Hatter HTML 5 currently does not support some formats with .mov videos, so for .mov videos, we will use images to display (in your example we are using gif images) Please use a different format video for NFT
> > 
> > 
> > @Pellar-LocNgo . Ok, this is an issue as the artist would have to burn these NFTs and upload the entire batch again using a different format.
> > He has over 100 NFTs and doing this manually would take ages. Please advise.
> 
> Hi @Pellar-LocNgo, any update on how we can solve this issue. How can the artists correct this issue, can they burn their NFTs from the platform and re-mint in a different format?

@pellarboss, would like to have an update on this issue, please? If HTML 5 can't show existing .mov files, how can we update these videos to correctly show as the artist originally intended? I am being chased to provide a solution for this. 

The same issue is happening to our stake-boosting NFTs where the video is cut short and then resets. 

Thanks
